apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-service
  description: Core Service responsible for core application logic.
  tags:
    - microservice
  annotations:
    github.com/project-slug: goafabric/core-service
    github.com/actions: goafabric/core-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: https://github.com/goafabric/backstage/tree/main/catalog/core/core-service/adrs

spec:
  type: service
  lifecycle: production
  owner: team-blue
  providesApis:
    - core-api
  dependsOn:
    - resource:core-db
    - resource:kafka
  links:
    - url: https://github.com/goafabric/core-service
      title: GitHub Repository
    - url: https://v2202402203466256255.megasrv.de/core/
      title: Service URL

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: core-api
  description: OpenAPI definition for Core Service.
  tags:
    - openapi
    - core-service
spec:
  type: openapi
  lifecycle: production
  owner: team-blue
  definition:
    $text: https://github.com/goafabric/core-service/blob/refactoring/doc/generated/openapi.json

