apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-fe
  description: The fundamental core app of the system
  tags:
    - npm
    - typescript
  annotations:
    github.com/project-slug: goafabric/core-fe

spec:
  type: service
  lifecycle: production
  owner: team-yellow
  system: goafabric-system
  consumesApis:
    - core-api
    - catalog-api
  dependsOn:
    - component:core-service
    - component:catalog-service
  links:
    - url: https://github.com/goafabric/core-fe
      title: GitHub Repository
    - url: https://v2202402203466256255.megasrv.de/core-fe/
      title: Service URL

