apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: blue
spec:
  type: team
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: green
spec:
  type: team
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: yellow
spec:
  type: team
  children: [ ]

