apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: invoice-process
  description: The fundamental core app of the system
  tags:
    - process
  annotations:
    github.com/project-slug: goafabric/invoice-process
    backstage.io/adr-location: https://github.com/goafabric/backstage/tree/main/catalog/core/invoice-process/adrs

spec:
  type: service
  lifecycle: production
  owner: team-blue
  
#  consumesApis:
#    - core-api
#    - catalog-api
  providesApis:
    - invoice-api
  dependsOn:
    - component:core-service
    - component:catalog-service
    - resource:kafka
  links:
    - url: https://github.com/goafabric/invoice-process
      title: GitHub Repository

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: invoice-api
  description: OpenAPI definition for Core Service.
  tags:
    - openapi
    - invoice-process
spec:
  type: openapi
  lifecycle: production
  owner: team-blue
  definition:
    $text: https://github.com/goafabric/invoice-process/blob/refactoring/doc/generated/openapi.json
