apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: invoice-process
  description: The fundamental core app of the system
  tags:
    - spring-boot
    - java
    - microservice
  annotations:
    github.com/project-slug: goafabric/invoice-process

spec:
  type: service
  lifecycle: production
  owner: team-blue
  
#  consumesApis:
#    - core-api
#    - catalog-api
  dependsOn:
    - component:core-service
    - component:catalog-service
    - resource:kafka
  links:
    - url: https://github.com/goafabric/invoice-process
      title: GitHub Repository
    - url: https://v2202402203466256255.megasrv.de/invoice-process/
      title: Service URL
