apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: person-service
  description: |
    The Person Service for managing person-related data
    
    [![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
    [![Coverage](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=coverage)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)

    [![Security Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=security_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
    [![Reliability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=reliability_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
    [![Maintainability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=sqale_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
  tags:
    - spring-boot
    - microservice
  annotations:
    github.com/project-slug: goafabric/person-service
  links:
    - url: https://github.com/goafabric/person-service
      title: GitHub Repository
spec:
  type: service
  lifecycle: production
  owner: team-green
  
  providesApis:
    - person-api
    - person-topic
    - person-async-topic
  dependsOn:
    - component:callee-service

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-api
  description: OpenAPI definition for Core Service.
  tags:
    - openapi
    - person-service-service
spec:
  type: openapi
  lifecycle: production
  owner: team-blue
  definition:
    $text: https://github.com/goafabric/person-service/blob/develop/doc/generated/openapi.json

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service
spec:
  type: kafka-topic
  lifecycle: production
  owner: devops
  definition: |
    topic: person
    type:  person
    key: person_id
    EventData.operation: CREATE | UPDATE | DELETE

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service
spec:
  type: openapi
  lifecycle: production
  owner: devops
  definition: |
    topic: person
    type:  person
    key: person_id
    EventData.operation: CREATE | UPDATE | DELETE

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-async-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service
spec:
  type: asyncapi
  lifecycle: production
  owner: devops
  definition: |
    asyncapi: 3.0.0
    info:
      title: Person Event Producer
      version: 1.0.1
      description: >
        AsyncAPI definition for Kafka events published to the `person` topic.
        Each message represents an `EventData` record emitted when a person-related entity changes.
    
    servers:
      kafkaBroker:
        host: kafka:9092
        protocol: kafka
    
    channels:
      person:
        address: person
        description: >
          The Kafka topic where person-related events are published.
        messages:
          eventDataMessage:
            $ref: '#/components/messages/EventDataMessage'
        bindings:
          kafka:
            topic: person
            bindingVersion: '0.4.0'
    
    operations:
      publishPersonEvent:
        action: send
        summary: Publish a person-related event.
        channel:
          $ref: '#/channels/person'
        messages:
          - $ref: '#/channels/person/messages/eventDataMessage'
    
    components:
      messages:
        EventDataMessage:
          name: EventData
          title: Person Event
          summary: Event data about a person or related address.
          contentType: application/json
          payload:
            $ref: '#/components/schemas/EventData'
          bindings:
            kafka:
              key:
                type: string
                description: The person ID used as the Kafka message key.
    
      schemas:
        EventData:
          type: object
          properties:
            type:
              type: string
              example: address
              description: The type of the event (e.g., address, contact, etc.)
            operation:
              type: string
              enum: [CREATE, UPDATE, DELETE]
              description: The CRUD operation type.
            payload:
              type: object
              description: Arbitrary event payload data.
            tenantInfos:
              type: object
              additionalProperties:
                type: string
              description: Tenant information as key-value pairs.
          required:
            - type
            - operation
            - payload


