apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: person-service
  description: |
    The Person Service for managing person-related data
    
    [![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=alert_status)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
    [![Coverage](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=coverage)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)

    [![Security Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=security_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
    [![Reliability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=reliability_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
    [![Maintainability Rating](https://sonarcloud.io/api/project_badges/measure?project=org.goafabric%3Aperson-service&metric=sqale_rating)](https://sonarcloud.io/summary/new_code?id=org.goafabric%3Aperson-service)
  tags:
    - spring-boot
    - microservice
  annotations:
    github.com/project-slug: goafabric/person-service
  links:
    - url: https://github.com/goafabric/person-service
      title: GitHub Repository
spec:
  type: service
  lifecycle: production
  owner: team-green
  
  providesApis:
    - person-api
    - person-topic
    - person-async-topic
  dependsOn:
    - component:callee-service

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-api
  description: OpenAPI definition for Core Service.
  tags:
    - openapi
    - person-service-service
spec:
  type: openapi
  lifecycle: production
  owner: team-blue
  definition:
    $text: https://github.com/goafabric/person-service/blob/develop/doc/generated/openapi.json

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service
spec:
  type: kafka-topic
  lifecycle: production
  owner: devops
  definition: |
    topic: person
    type:  person
    key: person_id
    EventData.operation: CREATE | UPDATE | DELETE

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service
spec:
  type: openapi
  lifecycle: production
  owner: devops
  definition: |
    topic: person
    type:  person
    key: person_id
    EventData.operation: CREATE | UPDATE | DELETE

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-async-topic
  description: Person Example Topic
  tags:
    - kafka-topic
    - person-service
spec:
  type: asyncapi
  lifecycle: production
  owner: devops
  definition: |  
    asyncapi: 2.0.0
    info:
      title: Person
      version: '1.0.0'
      description: |
        Sends emails upon certain events
      license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
    
    servers:
      production:
        url: mqtt://test.mosquitto.org
        protocol: mqtt
        description: Test MQTT broker
    
    channels:
      user/signedup:
        publish:
          operationId: onUserSignUp
          message:
            $ref : '#/components/messages/UserSignedUp'
    
    components:
      messages:
        UserSignedUp:
          name: userSignedUp
          title: User signed up event
          summary: Inform about a new user registration in the system
          contentType: application/json
          payload:
            $ref: '#/components/schemas/userSignedUpPayload'
    
      schemas:
        userSignedUpPayload:
          type: object
          properties:
            firstName:
              type: string
              description: "foo"
            lastName:
              type: string
              description: "bar"
            email:
              type: string
              format: email
              description: "baz"
            createdAt:
              type: string
              format: date-time
              description: "foo"